propeller:
  aid: "YOUR_AID"
  tid: "YOUR_TID"
  postback_url: "http://ad.propellerads.com/conversion.php"

galaksion:
  cid: "46704"
  postback_url: "http://postback.report/postback"

popcash:
  aid: "494669"
  type: "1"
  postback_url: "https://ct.popcash.net/click"

clickadilla:
  postback_url: "https://tracking.clickadilla.com/in/postbacks/"
  token: "m96gRV"

products:
  - name: "Shopee Direct - Anwar"
    url: "https://s.shopee.co.id/5VLlFD7dZe?sub_id={click_id--{campaign_id}--{spot_id}--{type_ads}--{domain}"
    percentage: 25.0

  - name: "Shopee Direct - Rima"
    url: "https://s.shopee.co.id/40X6O25UZO?sub_id={click_id--{campaign_id}--{spot_id}--{type_ads}--{domain}"
    percentage: 25.0

  - name: "Accesstrade - Shopee ID KOL Tier 1"
    url: "https://atid.me/0095ot002lt5?utm_source={spot_id}--{domain}--{type_ads}"
    percentage: 25.0

  - name: "Lazada Direct - Product Recommendation"
    url: "https://c.lazada.co.id/t/c.1AtgLz?sub_id1={siteid}&sub_id2={sub_id}&sub_id3={type_ads}&sub_aff_id={sub_id}"
    percentage: 5.0

  - name: "Lazada Direct - 9.9 Mega Brand Sale - Bonus offer"
    url: "https://c.lazada.co.id/t/c.c1Yk9D?sub_id1={siteid}&sub_id2={sub_id}&sub_id3={type_ads}&sub_aff_id={sub_id}"
    percentage: 5.0

  - name: "Lazada Direct - Buy at Best Price"
    url: "https://c.lazada.co.id/t/c.c1Yk9A?sub_id1={siteid}&sub_id2={sub_id}&sub_id3={type_ads}&sub_aff_id={sub_id}"
    percentage: 5.0

  - name: "Accesstrade - Lazada Kol"
    url: "https://atid.me/0082ly002lt5?utm_source={spot_id}--{domain}--{type_ads}"
    percentage: 5.0

  - name: "Ecomobi - Tiktok Shop"
    url: "https://goeco.mobi/IZ8PRcbo?sub1={spot_id}--{domain}--{type_ads}--{campaign_id}--{sub_id}"
    percentage: 2.5

  - name: "Involve - Traveloka"
    url: "https://invl.me/clmyea0"
    percentage: 2.5
